appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: q6K/PcoW9YyVH63cbT+XbCgdm93pevZ3QEvQRWuhOKI2koHbgKa9M0Pv5SGpq9s6w8qGQepo8ndtiBacogKg3oGTtV4qHOWEMXR+vKE+XK7U+Ln/wfcljCbkCRuD6l+K97LtKyeIJwA1LrzlBrZ6vnCTcIsLtItuRgMHxOwcpGSiWzhxe1D4q025Bn0p2z6QuZnTjwmICVPIlCO6Y/iYTWoqwqT56O+igCiEOpqiqm065lX6K5BmkoDgYCmF+81/ZyW6eEcVhfZKjUlZqtJqu1f05sH7DPy1vEgjD9KLcPxtkbEznWhpoPwe5nwVOLje9zm6irFYGUYmK87XS34au2moBFha9jWJR9H4CEN4YjEwsgTcIPB1QU0QHTHRxsfok8oPe2m251bUno2Km+xu9wsei4MUVONhAx610inwaEiiRQNqsrfzqg6Ia+OU+bKA98F5R9/pWc4/x40XV7nba7ewDFaAxNGoYlWnimpby0eD9FC2ZUCu+Ylxn9Pv+NSrteKb1w1Z1/kLBGFZv9KfFFjmiGTy/FSHkBeHQOLgvpW4ITiS397BynJiawXTViOyADTfC4H6Ugf4hwHm7az5rIqxFdpOAy8/FO3C6960sz6GiyQRtZCZguSAsPe5eFjqPQvSTUdwJPuRMNJlBajDLerxVEkkpqIXHyCFKMDn6Ko=}
